# Permalinks
permalink:           none
relative_permalinks: true

# Setup
title:               Mario Young
paginate:            10
paginate_path:       "page/:num"
baseurl:             ""
assets:              "/assets"
uploads:             "/uploads"
url:                 "http://maye.co"

github:
  repository_url: https://github.com/mayeco/mayeco.github.io
  branch: master

author:
  name:           Mario Young
  twitter:        mayeco
  google_plus:    MarioYoungURL
  github:         mayeco

sass:
  sass_dir:          _sass
  style:            :compressed

gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile

markdown:       kramdown
markdown_ext:   markdown,mkd,mkdn,md
highlighter:    pygments

# Compress HTML
compress_html: true
